version: "3.5"

services:
  hubble:
    image: "hubble.farcaster.dnp.dappnode.eth:1.10.0"
    build:
      context: .
      args:
        UPSTREAM_VERSION: 1.10.0
    # pull_policy: always
    # restart: on-failure:5
    restart: unless-stopped
    # command: [
    #   "node", "--no-warnings", "--max-old-space-size=8192",  "build/cli.js", "start",
    #   "--ip", "0.0.0.0",
    #   "--gossip-port", "${GOSSIP_PORT:-2282}",
    #   "--rpc-port", "${RPC_PORT:-2283}",   
    #   "--eth-mainnet-rpc-url", "$ETH_MAINNET_RPC_URL",
    #   "--l2-rpc-url", "$OPTIMISM_L2_RPC_URL",
    #   "--network", "${FC_NETWORK_ID:-1}",
    #   "--rpc-subscribe-per-ip-limit", "${RPC_SUBSCRIBE_PER_IP_LIMIT:-4}",
    #   "-b", "${BOOTSTRAP_NODE:-/dns/nemes.farcaster.xyz/tcp/2282}",
    #   "--statsd-metrics-server", "$STATSD_METRICS_SERVER",
    #   "--hub-operator-fid", "${HUB_OPERATOR_FID:-0}",
    # ]
    ports:
      - '2281:2281/tcp' # HTTP API. You can set HTTP_PORT in .env
      - '2282:2282/tcp' # Gossip. You can set GOSSIP_PORT in .env
      - '2282:2282/udp' # Gossip. You can set GOSSIP_PORT in .env
      - '2283:2283/tcp' # RPC. You can set RPC_PORT in .env
      - '2283:2283/udp' # RPC. You can set RPC_PORT in .env
    volumes:
      - hub:/home/node/app/apps/hubble/.hub
      - rocks:/home/node/app/apps/hubble/.rocks
    networks:
      - hubble-network
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "2"
    environment:
      EXTRA_OPTs: ""
      HTTPAPI_PORT: "2281"
      GOSSIP_PORT: "2282"
      RPC_PORT: "2283"
      # --eth-mainnet-rpc-url $ETH_MAINNET_RPC_URL \
      # --l2-rpc-url $OPTIMISM_L2_RPC_URL \
      RPC_SUBSCRIBE_PER_IP_LIMIT: "4"
      FC_NETWORK_ID: "1"
      BOOTSTRAP_NODE: "/dns/nemes.farcaster.xyz/tcp/2282"
      # --statsd-metrics-server $STATSD_METRICS_SERVER \
      HUB_OPERATOR_FID: "0"
  
  # Start this if you want perf metrics for your hubble node. Remember to start `grafana` as well.
  statsd:
    image: graphiteapp/graphite-statsd:1.1.10-5
    restart: unless-stopped
    ports:
      # - '80:80' # Graphite web
      # - '2003:2003' # Carbon line receiver
      # - '2004:2004' # Carbon pickle receiver
      # - '7002:7002' # Carbon cache query
      - '8125:8125/udp' # StatsD
      - '8126:8126' # StatsD admin
    networks:
      - hubble-network

  # Start this if you want to see perf metrics for your hubble node. Remember to start `statsd` as well.
  grafana:
    image: grafana/grafana:10.0.3
    restart: unless-stopped
    # Mount the grafana config file
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana  # Persistent Grafana data
    ports:
      - '3000:3000' # Grafana web
    networks:
      - hubble-network

networks:
  hubble-network:

volumes:
  hub: {}
  rocks: {}